
title: Challenge
email: your-email@example.com
description: "Veni // Vidi // Vici"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

#menu item list

menu:
- {name: About me, url: '#about-me'}
- {name: Challenge, url: '#challenge'}
- {name: Clients, url: '#clients'}
- {name: Contacts, url: '#contacts'}

blurb: <p><strong> Here is suppost to be a lot of information about me, my self and my skills</strong> but this part is optional,
        I was just playing around with fucntionality and got a bit destracted from the actual challenge
        </p> 
  

#Skill List

skills:
- {name: Comunication, value: '10'}
- {name: Learning, value: '10'}
- {name: Hobbies, value: '10'}
- {name: Team Player, value: '10'}
- {name: Programming, value: '6'}
- {name: Real Life, value: '10'}


#Work Section
- {name: Comunication, value: '10'}
- {name: Learning, value: '10'}